server:
  port: ${SPRINGBOOT_SERVER_PORT:8082}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/chat}

spring:
  application:
    name: chatting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://matching.169.56.100.104.nip.io:30503/matching}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:passw0rd}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:169.56.100.104}:${KAFKA_BROKER_PORT:30011}
    listener:
      ack-mode: MANUAL_IMMEDIATE
    producer:
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${CONSUMER_GROUP:chatting}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30 
  #type-aliases-package: com.matching.kb40.backend

#Parameter
param:
  kafka:
    topic:
        total:
          insert: chat_insert
          update: chat_update


# 추후에 변경할 것
# kafka-headless.default

## Old Version
#kafka:
#  bootstap-servers: localhost:9002
#  username: username
#  password: qwer!@#
#  enable:
#    auto:
#      commit: false
#  ackmode: MANUAL
#  offset:
#    reset: latest
#  concurrency: 3


